/* 
- Paquete de fuentes que almacenará los archivos SQL
 */
/**
 * Author:  cadit
 * Created: 13 abr. 2020
 */
DROP TABLE SERIE; /* IMPORTANTE: Debemos borrar primero la tabla principal debido a las PK*/
DROP TABLE GENERO;
CREATE TABLE GENERO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO CHAR(2),
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT ID_GENERO_PK PRIMARY KEY (ID)
);


CREATE TABLE SERIE (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    TÍTULO VARCHAR(20) NOT NULL,
    GENERO INTEGER NOT NULL,
    FECHA_ESTRENO DATE,
    CAPITULOS SMALLINT,
    PRECIO DECIMAL(7,2),
    VALORACION BOOLEAN,
    VISIONADA BOOLEAN,
    FOTO VARCHAR(30),
    CONSTRAINT ID_SERIE_PK PRIMARY KEY (ID),
    CONSTRAINT PROV_SERIE_FK FOREIGN KEY (GENERO) REFERENCES GENERO (ID)
);